// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createConversation: (input: CreateConversationInput_Deserialize) => typedError<ConversationRow, AppError>(__TAURI_INVOKE("create_conversation", { input })),
	listConversations: () => typedError<ConversationSummary_Serialize[], AppError>(__TAURI_INVOKE("list_conversations")),
	renameConversation: (id: string, title: string) => typedError<ConversationRow, AppError>(__TAURI_INVOKE("rename_conversation", { id, title })),
	/**
	 *  自动生成会话标题（LLM 概括首条用户消息）。
	 * 
	 *  触发时机：前端在首条 AI 回复结束后调用，且仅当当前标题仍是默认 “新会话”
	 *  （避免覆盖用户手动改名）。
	 * 
	 *  流程：
	 *    1. 取该会话首条 user 消息文本
	 *    2. 调 `ChatService::generate_title`（同 provider 轻量 LLM 补全）
	 *    3. 写回 `rename_conversation`
	 * 
	 *  失败时返回 Err，前端降级为截断式兜底（deriveTitle）。
	 *  标题为空或仍为默认值时返回 Err，提示前端走兜底。
	 */
	generateConversationTitle: (id: string) => typedError<ConversationRow, AppError>(__TAURI_INVOKE("generate_conversation_title", { id })),
	setConversationPinned: (input: SetPinnedInput) => typedError<null, AppError>(__TAURI_INVOKE("set_conversation_pinned", { input })),
	deleteConversation: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_conversation", { id })),
	listMessages: (conversationId: string, limit: number | null) => typedError<MessageRow_Serialize[], AppError>(__TAURI_INVOKE("list_messages", { conversationId, limit })),
	deleteMessage: (input: DeleteMessageInput) => typedError<null, AppError>(__TAURI_INVOKE("delete_message", { input })),
	setMessageStatus: (input: SetMessageStatusInput_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("set_message_status", { input })),
	sendMessage: (input: SendMessageInput, onChunk: Channel<ChatStreamChunk_Deserialize>) => typedError<string, AppError>(__TAURI_INVOKE("send_message", { input, onChunk })),
	/**
	 *  中断指定 assistant 消息的流式生成。
	 *  触发 send_message 注册的 oneshot cancel sender → 流循环 select! 退出 → 落库 Cancelled。
	 */
	cancelStream: (messageId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_stream", { messageId })),
	setProvider: (input: SetProviderInput_Deserialize) => typedError<ProviderConfig_Serialize, AppError>(__TAURI_INVOKE("set_provider", { input })),
	getProvider: () => typedError<{
	kind: ProviderKind,
	/**  API Key（明文，一期；二期落 Rust 侧加密存储） */
	api_key: string,
	/**  自定义 base URL。None 则用 provider 默认（rig 内置各 provider 的 BASE_URL 常量）。 */
	base_url?: string | null,
	/**  模型名，如 "gpt-4o" / "claude-sonnet-4-5" / "deepseek-chat" / "gemini-2.5-pro" */
	model: string,
	/**  采样温度。知识工作台常需低温度（factual 输出）。None 用 provider 默认。 */
	temperature?: number | null,
	/**
	 *  最大输出 token 数。区别于 context_window（输入窗口）。
	 *  None 时 Anthropic 用 provider 默认（4096）；OpenAI 不设（无上限）。
	 */
	max_tokens?: number,
	/**  nucleus sampling。None 不设。走 additional_params 透传。 */
	top_p?: number | null,
	/**
	 *  是否支持 `developer` role。false 时降级为 `system` message（Ollama/vLLM 等）。
	 *  None 用 kind 默认（OpenAI 官方 true，兼容端点 false）。
	 */
	supports_developer_role?: boolean | null,
	/**
	 *  是否支持 `reasoning_effort` 参数。false 时 drop（兼容端点不认）。
	 *  None 用 kind 默认。
	 */
	supports_reasoning_effort?: boolean | null,
	/**  模型支持输入模态。默认 [Text]；多模态模型填 [Text, Image]。 */
	input_types: InputType[],
	/**
	 *  模型上下文窗口（token 数）。可选，用户显式覆盖。
	 * 
	 *  优先级最高（见 context_window::resolve_context_window）：
	 *    用户配置 > 官方元数据探测（按 kind 分派）> 内置已知模型表 > 默认 100K
	 *  None 时自动探测（OpenRouter/Anthropic/Gemini 读官方字段；
	 *  DeepSeek 等无官方元数据的模型走内置表）。
	 *  探测全程超时+错误保护，不影响对话主流程；真正的安全网是运行时
	 *  usage + overflow 错误恢复（见 chat.rs / 决策 16）。
	 */
	context_window?: number,
	/**
	 *  系统人设（preamble）。可选，用户在设置页配置。
	 * 
	 *  Skill 系统首次引入 preamble 机制（决策 20）：系统人设 + Skill Tier 1
	 *  （<available_skills> 块）拼接为完整 preamble，注入 AgentBuilder::preamble。
	 *  拼在系统人设后，不破坏 prefix cache（前缀不变，skill 段是后缀追加）。
	 *  None 时仅用 skill 段（若无 skill 则无 preamble）。
	 */
	preamble?: string | null,
	/**
	 *  自定义 HTTP Header（代理、OpenRouter X-Title、Anthropic anthropic_betas 等）。
	 *  键值对，构造 client 时合并进 `Client::builder().http_headers()`。
	 */
	extra_headers?: { [key in string]: string } | null,
	/**  深度思考配置。None 等同 Off。 */
	reasoning?: ReasoningLevel | null,
} | null, AppError>(__TAURI_INVOKE("get_provider")),
	/**
	 *  配置并连接 MCP server（整体替换）。
	 * 
	 *  传入完整 server 列表，命令：
	 *    1. 持久化配置到 store
	 *    2. drop 旧 McpManager（断开旧连接）
	 *    3. 新建 McpManager 连接所有 server，工具注册到共享 tool_handle
	 *    4. 把 tool_handle 注入 ChatService（若已配置）
	 * 
	 *  返回每个 server 的连接状态。单个失败不影响其他。
	 */
	setMcpServers: (servers: McpServerConfig[]) => typedError<McpServerStatus_Serialize[], AppError>(__TAURI_INVOKE("set_mcp_servers", { servers })),
	/**  读取已持久化的 MCP server 配置（不含连接状态，启动恢复用）。 */
	getMcpServers: () => typedError<McpServerConfig[], AppError>(__TAURI_INVOKE("get_mcp_servers")),
	/**  列出当前 tool_handle 上注册的所有工具（已连接 MCP server 暴露的工具）。 */
	listMcpTools: () => typedError<McpToolDef[], AppError>(__TAURI_INVOKE("list_mcp_tools")),
	/**
	 *  摄取一批文件（batch 级并行）。
	 * 
	 *  流程（§14.2）：
	 *  1. 为每个 path 生成 job_id，注册 cancel flag，发 Queued
	 *  2. 用 `JoinSet` + 信号量限并发，每个文件 `spawn_blocking` 串行解析
	 *  3. 各文件独立发 Parsing 进度（经节流桥接）→ Done/Error/Cancelled
	 * 
	 *  单文件内串行（保逐页进度 + 可取消），多文件并行（限并发数）。
	 */
	ingestFiles: (paths: string[], onProgress: Channel<IngestProgress>, conversationId: string | null, folderPath: string | null) => typedError<IngestResultItem[], AppError>(__TAURI_INVOKE("ingest_files", { paths, onProgress, conversationId, folderPath })),
	/**
	 *  取消指定摄取任务（cooperative）。
	 * 
	 *  parser 在下一次循环边界检查到 cancel flag 后 break，返回 Cancelled。
	 *  对底层库内部阻塞（如 lopdf::Document::load）无法立即中止——只在循环点生效。
	 */
	cancelIngest: (jobId: string) => typedError<boolean, AppError>(__TAURI_INVOKE("cancel_ingest", { jobId })),
	/**
	 *  挂载文档到会话（`@` 挂载持久化）。幂等。
	 *  path 必须先经 ingest 摄取（documents 表已有该 path）。
	 */
	mountDocument: (conversationId: string, path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("mount_document", { conversationId, path })),
	/**  卸载会话下的某篇文档（不删 documents 全文）。 */
	unmountDocument: (conversationId: string, path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("unmount_document", { conversationId, path })),
	/**  列出会话已挂载的文档（按挂载时间排序，不含全文）。 */
	listMountedDocuments: (conversationId: string) => typedError<MountedDocDto[], AppError>(__TAURI_INVOKE("list_mounted_documents", { conversationId })),
	/**  列出知识库全部入库文档（不含全文，`@` 菜单选择挂载用）。 */
	listAllDocuments: () => typedError<DocumentSummaryDto[], AppError>(__TAURI_INVOKE("list_all_documents")),
	/**  按 path 删除知识库文档（同时清 FTS5 索引 + 所有会话的挂载关联）。 */
	deleteDocument: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("delete_document", { path })),
	/**  按 id 读取文档全文（可分页，预览用）。 */
	readDocument: (id: string, offset: number | null, limit: number | null) => typedError<{
	path: string,
	name: string,
	format: string,
	text: string,
	char_count: number,
} | null, AppError>(__TAURI_INVOKE("read_document", { id, offset, limit })),
	/**  注册数据源（落 SQLite + 热注册到 SessionContext + 探测连接）。 */
	registerDataSource: (config: DataSourceConfig_Deserialize) => typedError<DataSourceSummary_Serialize, AppError>(__TAURI_INVOKE("register_data_source", { config })),
	/**  测试连接（临时注册探查后注销，不落库）。返回表结构快照。 */
	testDataSource: (config: DataSourceConfig_Deserialize) => typedError<SchemaSnapshot_Serialize, AppError>(__TAURI_INVOKE("test_data_source", { config })),
	/**
	 *  注销数据源（删 SQLite 记录；SessionContext 内 catalog 随进程生命周期留存，
	 *  重启不恢复——DF 54 无 deregister_catalog，见 catalog.rs）。
	 */
	deregisterDataSource: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("deregister_data_source", { id })),
	/**  列出所有已注册数据源（含连接状态/表数）。 */
	listDataSources: () => typedError<DataSourceSummary_Serialize[], AppError>(__TAURI_INVOKE("list_data_sources")),
	/**  取单个数据源配置（编辑用）。 */
	getDataSource: (id: string) => typedError<{
	id: string,
	name: string,
	connection: ConnectionConfig_Serialize,
	/**  连接颜色标记（DBX 范式：红=生产/蓝=测试/绿=本地）。 */
	color?: string | null,
	/**  创建时间（unix ms）。 */
	created_at: number,
} | null, AppError>(__TAURI_INVOKE("get_data_source", { id })),
	/**  浏览 catalog 下所有表结构（不含样本行，list_tables 工具）。 */
	browseFederationSchema: (catalog: string) => typedError<SchemaSnapshot_Serialize, AppError>(__TAURI_INVOKE("browse_federation_schema", { catalog })),
	/**  描述单表：列/类型/可空 + 前 5 行样本 + 行数估计（describe_table 工具）。 */
	describeFederationTable: (catalog: string, table: string) => typedError<TableMeta_Serialize, AppError>(__TAURI_INVOKE("describe_federation_table", { catalog, table })),
	/**  执行只读 SQL（三段式寻址 catalog.public.table）。自动追加 LIMIT，30s 超时。 */
	executeFederationQuery: (sql: string, limit: number | null) => typedError<QueryResult_Serialize, AppError>(__TAURI_INVOKE("execute_federation_query", { sql, limit })),
	/**  EXPLAIN：生成执行计划摘要（调试/审计，本身只读）。 */
	explainFederationQuery: (sql: string) => typedError<string, AppError>(__TAURI_INVOKE("explain_federation_query", { sql })),
	/**
	 *  新建空文件夹（持久化到 folders 表）。
	 *  path 如 "/曾国藩专题" 或 "/曾国藩专题/书信集"。自动推导 parent_path/name。
	 *  已存在则忽略（幂等）。返回是否实际创建。
	 */
	createFolder: (path: string) => typedError<boolean, AppError>(__TAURI_INVOKE("create_folder", { path })),
	/**
	 *  列出文件夹树（后端已构建嵌套层级 + 排序，前端直接渲染）。
	 * 
	 *  替代旧版扁平 `list_folders` 返回 `Vec<String>` 的做法——
	 *  树构建是领域逻辑，不应在前端解析 `/` 拆分。
	 */
	listFolders: () => typedError<FolderNodeDto[], AppError>(__TAURI_INVOKE("list_folders")),
	/**
	 *  列出指定文件夹下的直接子文件（Library 右栏展示）。
	 *  folder = null 或 "/" 表示根目录散文件（folder_path IS NULL）。
	 */
	listDocumentsByFolder: (folder: string | null) => typedError<DocumentSummaryDto[], AppError>(__TAURI_INVOKE("list_documents_by_folder", { folder })),
	/**  移动单个文件到目标文件夹。target_folder=null 表示根目录散文件。 */
	moveDocument: (path: string, targetFolder: string | null) => typedError<boolean, AppError>(__TAURI_INVOKE("move_document", { path, targetFolder })),
	/**
	 *  重命名文件夹（递归处理子文件夹）。
	 *  old_path 如 "/曾国藩专题", new_path 如 "/曾公研究"。
	 */
	renameFolder: (oldPath: string, newPath: string) => typedError<boolean, AppError>(__TAURI_INVOKE("rename_folder", { oldPath, newPath })),
	/**
	 *  删除文件夹及其下所有文件（含子文件夹递归）。
	 *  每个文件走 delete_document_by_path（清 documents 行 + FTS5 索引 + conversation_documents 关联）。
	 *  返回删除的文件数。
	 */
	deleteFolder: (folder: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_folder", { folder })),
	/**  读取会话激活集。 */
	getActiveScope: (conversationId: string) => typedError<ActiveScopeDto, AppError>(__TAURI_INVOKE("get_active_scope", { conversationId })),
	/**  设置会话激活集的文件夹部分。 */
	setActiveFolders: (conversationId: string, folders: string[]) => typedError<null, AppError>(__TAURI_INVOKE("set_active_folders", { conversationId, folders })),
	/**  设置会话激活集的数据源部分。 */
	setActiveSources: (conversationId: string, sources: string[]) => typedError<null, AppError>(__TAURI_INVOKE("set_active_sources", { conversationId, sources })),
	/**
	 *  设置会话激活集的本体部分（@OntologyName 引用本体）。
	 * 
	 *  存 ontology api_name 列表。传入空 Vec 清空引用。
	 *  会话模式挂 5 个只读 drill-in 工具，agent 按 api_name 钻取 schema（不注入全文）。
	 */
	setActiveOntologies: (conversationId: string, ontologies: string[]) => typedError<null, AppError>(__TAURI_INVOKE("set_active_ontologies", { conversationId, ontologies })),
	/**
	 *  列出全部已发现的 skill，合并激活状态。
	 * 
	 *  `conversation_id` 为 None 时只返回全局状态（conversation_enabled 全 None）。
	 * 
	 *  扫盘是同步磁盘 IO，放 spawn_blocking 避免阻塞 async runtime；外加超时
	 *  兑底（SkillManager 内部有 single-flight + 60s TTL 缓存，正常路径秒回）。
	 */
	listSkills: (conversationId: string | null) => typedError<SkillDto[], AppError>(__TAURI_INVOKE("list_skills", { conversationId })),
	/**  导入本地 skill 目录（复制到 ~/.onto-studio/skills/<name>/）。 */
	importSkillFromDir: (srcPath: string) => typedError<string, AppError>(__TAURI_INVOKE("import_skill_from_dir", { srcPath })),
	/**  导入 zip skill（解压 + 校验 + 复制）。 */
	importSkillFromZip: (zipPath: string) => typedError<string, AppError>(__TAURI_INVOKE("import_skill_from_zip", { zipPath })),
	/**  卸载导入的 skill（仅 imported 可卸载）。 */
	uninstallSkill: (skillName: string) => typedError<null, AppError>(__TAURI_INVOKE("uninstall_skill", { skillName })),
	/**
	 *  设置会话级 skill enabled 状态（层次 3）。
	 * 
	 *  enabled=true：Builtin/External 保持进 preamble，Imported 激活进 preamble；
	 *  enabled=false：Builtin/External 显式排除，Imported 不激活。
	 */
	setSkillConversationEnabled: (conversationId: string, skillName: string, source: SkillSource, enabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_skill_conversation_enabled", { conversationId, skillName, source, enabled })),
	/**  设置全局 skill 禁用状态（层次 2）。 */
	setSkillGloballyDisabled: (skillName: string, disabled: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_skill_globally_disabled", { skillName, disabled })),
	deleteMessageAndAfter: (input: DeleteMessageAndAfterInput) => typedError<number, AppError>(__TAURI_INVOKE("delete_message_and_after", { input })),
	/**  列出所有已存储本体（前端列表页用）。 */
	listOntologies: () => typedError<OntologySummary[], AppError>(__TAURI_INVOKE("list_ontologies")),
	/**
	 *  导出本体为 OntologyPayload JSON 字符串（write-view）。
	 *  前端 `JSON.parse` 后展示当前定义、或作为增量更新的起点。
	 */
	exportOntology: (ontologyApiName: string) => typedError<string, AppError>(__TAURI_INVOKE("export_ontology", { ontologyApiName })),
	/**
	 *  预演导入（dry-run）。返回 ImportPreview JSON 字符串。
	 *  **落库前必调**：前端解析后检查 errors 非空则阻止提交 import。
	 */
	previewOntologyImport: (payloadJson: string, overwriteObjectTypes: string[], overwriteDataSources: string[]) => typedError<string, AppError>(__TAURI_INVOKE("preview_ontology_import", { payloadJson, overwriteObjectTypes, overwriteDataSources })),
	/**
	 *  执行导入（DAG 顺序落库，best-effort 部分失败）。
	 *  返回 ImportResult JSON 字符串，前端解析后检查 per-entity 状态。
	 */
	importOntology: (payloadJson: string, overwriteObjectTypes: string[], overwriteDataSources: string[]) => typedError<string, AppError>(__TAURI_INVOKE("import_ontology", { payloadJson, overwriteObjectTypes, overwriteDataSources })),
	/**
	 *  删除本体及其全部子表（硬删，对齐 Gaia `hard_delete_ontology`）。
	 * 
	 *  依赖 DB `ON DELETE CASCADE` 级联清掉 object_types / properties / link_types /
	 *  action_types / object_type_groups 等。dataset / data_source 不删（物理资产
	 *  跨本体共享，设计决策 10）。
	 * 
	 *  返回是否真的删除了（false=未找到该本体，幂等不报错）。
	 */
	deleteOntology: (ontologyApiName: string) => typedError<boolean, AppError>(__TAURI_INVOKE("delete_ontology", { ontologyApiName })),
	/**
	 *  列出本体的变更历史（git commit log 式，revision 倒序）。
	 *  返回结构化 `Vec<OntologyChangelog>`（created_at 已标 Number，无 BigInt 问题）。
	 */
	listOntologyChangelog: (ontologyApiName: string) => typedError<OntologyChangelog_Serialize[], AppError>(__TAURI_INVOKE("list_ontology_changelog", { ontologyApiName })),
	/**
	 *  列出指定本体下的全部数据集（决策 10 修订：按本体隔离）。
	 * 
	 *  DatasetDef 含 `partition_config: Option<Value>`，serde_json::Value 触发
	 *  BigIntForbidden，故用 String（JSON）传输，前端 JSON.parse。
	 */
	listOntologyDatasets: (ontologyApiName: string) => typedError<string, AppError>(__TAURI_INVOKE("list_ontology_datasets", { ontologyApiName })),
	/**
	 *  列出指定本体下的全部数据源（决策 10 修订：按本体隔离）。
	 * 
	 *  DataSourceDef 含 `connector_config: Value`，同上用 String（JSON）传输。
	 */
	listOntologyDataSources: (ontologyApiName: string) => typedError<string, AppError>(__TAURI_INVOKE("list_ontology_data_sources", { ontologyApiName })),
	/**
	 *  读取本体设计宪章（不变点：业务场景 / 本质 / 设计意图 / 补充说明）。
	 * 
	 *  charter 不随历史变化——它记录本体的业务本质说明，不随实体增删改而变更。
	 *  由独立命令写入，不进 import 流程。前端详情页头部常驻展示。
	 */
	getOntologyCharter: (ontologyApiName: string) => typedError<OntologyCharter, AppError>(__TAURI_INVOKE("get_ontology_charter", { ontologyApiName })),
	/**
	 *  写入/更新本体设计宪章（不变点）。
	 * 
	 *  **只有用户明确要求调整 charter 时才调用**；常规增量更新不应触碰 charter。
	 *  `updated_by` 为 "agent" | "user"。写后不触发 ontology-changed（charter 不影响实体定义）。
	 */
	setOntologyCharter: (ontologyApiName: string, charter: OntologyCharter) => typedError<null, AppError>(__TAURI_INVOKE("set_ontology_charter", { ontologyApiName, charter })),
};

/* Types */
/**  会话激活集快照（供前端 chip 展示 + 工具过滤）。 */
export type ActiveScopeDto = {
	/**  激活的文件夹路径（含子目录递归）。 */
	folders: string[],
	/**  激活的单文件 path（@触发，conversation_documents 表）。 */
	documents: string[],
	/**  激活的数据源名。 */
	sources: string[],
	/**  激活的本体 api_name（@OntologyName 引用，如 ["SupplyChain"]）。 */
	ontologies: string[],
};

export type AppError = { kind: "Ingest"; message: string } | { kind: "Agent"; message: string } | { kind: "Memory"; message: string } | { kind: "Provider"; message: string } | { kind: "Federation"; message: string } | { kind: "Ontology"; message: string } | { kind: "Skill"; message: string } | { kind: "SkillScanTimeout"; message: string } | 
/**  用户主动中断（§15 状态机 Cancelled）——前端静默处理 */
{ kind: "Cancelled" };

/**
 *  流式 chunk（对齐 §13.2 StreamChunk，由 agent-core 的 StreamChunk 映射）。
 * 
 *  额外带 `message_id` 让前端定位 assistant 消息做增量 patch（§14.1 性能要点）。
 */
export type ChatStreamChunk = ChatStreamChunk_Serialize | ChatStreamChunk_Deserialize;

/**
 *  流式 chunk（对齐 §13.2 StreamChunk，由 agent-core 的 StreamChunk 映射）。
 * 
 *  额外带 `message_id` 让前端定位 assistant 消息做增量 patch（§14.1 性能要点）。
 */
export type ChatStreamChunk_Deserialize = {
	/**  assistant 消息 ID（首个 chunk 发出后前端据此 patch） */
	message_id: string,
	kind: StreamKind,
	text: string,
	/**  工具调用详情（仅 ToolCallStart/Result 有值） */
	tool_call: ToolCallInfo | null,
	/**  token usage（仅 Usage 有值；二期 B1） */
	usage: TokenUsage | null,
};

/**
 *  流式 chunk（对齐 §13.2 StreamChunk，由 agent-core 的 StreamChunk 映射）。
 * 
 *  额外带 `message_id` 让前端定位 assistant 消息做增量 patch（§14.1 性能要点）。
 */
export type ChatStreamChunk_Serialize = {
	/**  assistant 消息 ID（首个 chunk 发出后前端据此 patch） */
	message_id: string,
	kind: StreamKind,
	text: string,
	/**  工具调用详情（仅 ToolCallStart/Result 有值） */
	tool_call?: ToolCallInfo | null,
	/**  token usage（仅 Usage 有值；二期 B1） */
	usage?: TokenUsage | null,
};

/**  列元信息（information_schema.columns 子集）。 */
export type ColumnMeta = {
	name: string,
	/**  Arrow 类型名（如 Utf8、Int64、Float64、Date32）。 */
	data_type: string,
	/**  是否可空。 */
	nullable: boolean,
};

/**  连接配置（按 kind 分变体）。 */
export type ConnectionConfig = ConnectionConfig_Serialize | ConnectionConfig_Deserialize;

/**  连接配置（按 kind 分变体）。 */
export type ConnectionConfig_Deserialize = { kind: "mysql"; params: DbConnection_Deserialize } | { kind: "postgres"; params: DbConnection_Deserialize } | { kind: "csv"; params: FileConnection } | { kind: "excel"; params: FileConnection };

/**  连接配置（按 kind 分变体）。 */
export type ConnectionConfig_Serialize = { kind: "mysql"; params: DbConnection_Serialize } | { kind: "postgres"; params: DbConnection_Serialize } | { kind: "csv"; params: FileConnection } | { kind: "excel"; params: FileConnection };

/**  IPC 用图片上下文块。 */
export type ContextImageInput = {
	mime: string,
	data_b64: string,
};

/**  会话行（DB 行 ↔ 前端 DTO）。 */
export type ConversationRow = {
	id: string,
	title: string,
	created_at: number,
	updated_at: number,
	pinned: boolean,
};

/**  会话 + 首条预览（侧栏列表用，避免一次拉全部消息）。 */
export type ConversationSummary = ConversationSummary_Serialize | ConversationSummary_Deserialize;

/**  会话 + 首条预览（侧栏列表用，避免一次拉全部消息）。 */
export type ConversationSummary_Deserialize = {
	/**  最近一条消息的纯文本预览（截断），无消息则为 None */
	last_message_preview: string | null,
	/**  消息条数 */
	message_count: number,
} & ConversationRow;

/**  会话 + 首条预览（侧栏列表用，避免一次拉全部消息）。 */
export type ConversationSummary_Serialize = {
	/**  最近一条消息的纯文本预览（截断），无消息则为 None */
	last_message_preview?: string | null,
	/**  消息条数 */
	message_count: number,
} & ConversationRow;

export type CreateConversationInput = CreateConversationInput_Serialize | CreateConversationInput_Deserialize;

export type CreateConversationInput_Deserialize = {
	title: string | null,
};

export type CreateConversationInput_Serialize = {
	title?: string | null,
};

/**
 *  数据源完整配置（落 SQLite + 注册到 DataFusion catalog）。
 * 
 *  `name` 同时作为 catalog 名（三段式 `catalog.schema.table` 寻址用），
 *  必须唯一且合法（DataFusion catalog 名约束：字母数字下划线，不含点）。
 * 
 *  `id` 用 String 存 UUID v4（对齐 memory 的 conversation id 范式，
 *  避免 specta uuid feature 依赖）。
 */
export type DataSourceConfig = DataSourceConfig_Serialize | DataSourceConfig_Deserialize;

/**
 *  数据源完整配置（落 SQLite + 注册到 DataFusion catalog）。
 * 
 *  `name` 同时作为 catalog 名（三段式 `catalog.schema.table` 寻址用），
 *  必须唯一且合法（DataFusion catalog 名约束：字母数字下划线，不含点）。
 * 
 *  `id` 用 String 存 UUID v4（对齐 memory 的 conversation id 范式，
 *  避免 specta uuid feature 依赖）。
 */
export type DataSourceConfig_Deserialize = {
	id: string,
	name: string,
	connection: ConnectionConfig_Deserialize,
	/**  连接颜色标记（DBX 范式：红=生产/蓝=测试/绿=本地）。 */
	color?: string | null,
	/**  创建时间（unix ms）。 */
	created_at: number,
};

/**
 *  数据源完整配置（落 SQLite + 注册到 DataFusion catalog）。
 * 
 *  `name` 同时作为 catalog 名（三段式 `catalog.schema.table` 寻址用），
 *  必须唯一且合法（DataFusion catalog 名约束：字母数字下划线，不含点）。
 * 
 *  `id` 用 String 存 UUID v4（对齐 memory 的 conversation id 范式，
 *  避免 specta uuid feature 依赖）。
 */
export type DataSourceConfig_Serialize = {
	id: string,
	name: string,
	connection: ConnectionConfig_Serialize,
	/**  连接颜色标记（DBX 范式：红=生产/蓝=测试/绿=本地）。 */
	color?: string | null,
	/**  创建时间（unix ms）。 */
	created_at: number,
};

/**  数据源类型（三期范围：MySQL/PG/CSV/Excel）。 */
export type DataSourceKind = "mysql" | "postgres" | "csv" | "excel";

/**  数据源摘要（list_data_sources 工具 + 前端连接列表）。 */
export type DataSourceSummary = DataSourceSummary_Serialize | DataSourceSummary_Deserialize;

/**  数据源摘要（list_data_sources 工具 + 前端连接列表）。 */
export type DataSourceSummary_Deserialize = {
	id: string,
	name: string,
	kind: DataSourceKind,
	/**  当前连接状态（启动/注册时探测）。 */
	connected: boolean,
	/**  表数（已连接时；CSV/Excel = 文件内 sheet 数）。 */
	table_count: number,
	/**  最近一次连接/查询失败原因（前端展示 ⚠️）。 */
	last_error?: string | null,
};

/**  数据源摘要（list_data_sources 工具 + 前端连接列表）。 */
export type DataSourceSummary_Serialize = {
	id: string,
	name: string,
	kind: DataSourceKind,
	/**  当前连接状态（启动/注册时探测）。 */
	connected: boolean,
	/**  表数（已连接时；CSV/Excel = 文件内 sheet 数）。 */
	table_count?: number,
	/**  最近一次连接/查询失败原因（前端展示 ⚠️）。 */
	last_error?: string | null,
};

/**  数据库连接配置（MySQL/PG）。CSV/Excel 走 FileConnection。 */
export type DbConnection = DbConnection_Serialize | DbConnection_Deserialize;

/**  数据库连接配置（MySQL/PG）。CSV/Excel 走 FileConnection。 */
export type DbConnection_Deserialize = {
	host: string,
	port: number,
	database: string,
	username: string,
	/**  明文密码（三期，对齐决策 10）。二期迁 keyring 时改加密后端。 */
	password?: string | null,
	/**
	 *  SSL 模式：disable / require / verify（Beekeeper 三档范式）。
	 *  三期默认 require（rustls），verify 暂不校验 CA（桌面单用户）。
	 */
	ssl_mode?: string,
};

/**  数据库连接配置（MySQL/PG）。CSV/Excel 走 FileConnection。 */
export type DbConnection_Serialize = {
	host: string,
	port: number,
	database: string,
	username: string,
	/**  明文密码（三期，对齐决策 10）。二期迁 keyring 时改加密后端。 */
	password?: string | null,
	/**
	 *  SSL 模式：disable / require / verify（Beekeeper 三档范式）。
	 *  三期默认 require（rustls），verify 暂不校验 CA（桌面单用户）。
	 */
	ssl_mode: string,
};

/**
 *  删除指定消息及其之后的全部消息（用于重新生成 / 编辑重发）。
 *  返回被删除的消息条数（含目标消息自身）。
 */
export type DeleteMessageAndAfterInput = {
	message_id: string,
};

export type DeleteMessageInput = {
	message_id: string,
};

/**  文档全文内容（预览抽屉用）。 */
export type DocumentContentDto = {
	path: string,
	name: string,
	format: string,
	text: string,
	char_count: number,
};

/**  知识库全部入库文档的摘要（不含全文，`@` 菜单选择用）。 */
export type DocumentSummaryDto = {
	id: string,
	path: string,
	name: string,
	format: string,
	char_count: number,
	created_at: number,
	folder_path: string | null,
};

/**  文件型连接配置（CSV/Excel）。 */
export type FileConnection = {
	/**  源文件绝对路径。CSV 可指向目录（注册目录下所有 .csv）。 */
	path: string,
	/**  CSV 是否有表头（仅 CSV 有效）。 */
	has_header?: boolean,
	/**  CSV 分隔符（默认逗号）。TSV 用 "\t"。 */
	delimiter?: string,
};

/**
 *  文件夹树节点（后端构建层级，前端直接渲染）。
 * 
 *  文件夹由文件的 `folder_path` 隐式定义；后端从 DISTINCT folder_path
 *  构建嵌套树，Inbox 置顶，其余按名排序。把树构建放后端是因为层级解析 +
 *  排序是领域逻辑，不应散在前端。
 */
export type FolderNodeDto = {
	/**  当前层名字（不含路径前缀，如 "书信集"）。 */
	name: string,
	/**  完整路径（如 "/曾国藩专题/书信集"）。 */
	path: string,
	/**  子文件夹（已排序，Inbox 置顶）。 */
	children: FolderNodeDto[],
};

/**  单个摄取任务的进度事件（前端 IngestStatusBoard 据此更新卡片）。 */
export type IngestProgress = {
	job_id: string,
	path: string,
	file_name: string,
	stage: IngestStage,
	/**  已产出字符数（parsing 阶段渐进更新）。 */
	char_count: number,
	/**  error 阶段的错误信息。 */
	error: string | null,
	/**  当前解析阶段描述（如 "提取 PDF 文本"）。仅在 parsing 阶段有意义。 */
	phase?: string | null,
	/**  细粒度进度：已处理单元数（页/章/条目）。仅在 parsing 阶段渐进更新。 */
	current?: number | null,
	/**  细粒度进度：总单元数；未知时为 None（前端显示 "current/?"）。 */
	total?: number | null,
	/**  文件大小（字节）。Queued 时即上报，供前端在文件名旁展示。 */
	file_size?: number,
};

/**
 *  摄取完成后的产物摘要（前端据此展示/挂载到会话）。
 *  不含全文——全文由 ingest_files 内部直接 upsert 到 documents 表，前端按需
 *  read_document(id) 取全文（决策 17：避免大全文经 IPC 往返，触发 payload 限制）。
 */
export type IngestResultItem = {
	job_id: string,
	path: string,
	file_name: string,
	format: string,
	char_count: number,
	/**  多模态 part 数（图片输入）。 */
	multimodal_count: number,
	/**  文件大小（字节）。 */
	file_size?: number,
};

export type IngestStage = "Queued" | "Parsing" | "Done" | "Error" | 
/**  用户取消 */
"Cancelled";

/**  模型输入模态（UI 据此显隐图片上传）。对齐 pi `input` 字段。 */
export type InputType = "text" | "image";

/**  单个 MCP server 的连接配置。 */
export type McpServerConfig = 
/**  stdio 子进程传输（本地 MCP server，如 `npx @modelcontextprotocol/server-filesystem`）。 */
{ kind: "stdio"; 
/**  唯一标识（前端展示与去重用）。 */
id: string; 
/**  展示名。 */
name: string; 
/**  可执行命令（如 "npx" / "node" / "uvx"）。 */
command: string; 
/**  命令参数。 */
args: string[]; 
/**  额外环境变量（追加到进程继承的环境）。 */
env?: { [key in string]: string } } | 
/**  HTTP / Streamable HTTP 传输（远程 MCP server）。 */
{ kind: "http"; 
/**  唯一标识。 */
id: string; 
/**  展示名。 */
name: string; 
/**  server URL（如 "https://example.com/mcp"）。 */
url: string; 
/**  可选 Bearer token（发送 `Authorization: Bearer <token>`）。 */
auth_token?: string | null; 
/**  可选自定义请求头。 */
headers?: { [key in string]: string } };

/**  MCP server 连接结果（单个 server 的状态）。 */
export type McpServerStatus = McpServerStatus_Serialize | McpServerStatus_Deserialize;

/**  MCP server 连接结果（单个 server 的状态）。 */
export type McpServerStatus_Deserialize = {
	/**  配置中的 server 名（前端展示用）。 */
	name: string,
	/**  是否连接成功。 */
	connected: boolean,
	/**  注册的工具数量（连接成功时）。 */
	tool_count: number,
	/**  失败原因（连接失败时）。 */
	error: string | null,
};

/**  MCP server 连接结果（单个 server 的状态）。 */
export type McpServerStatus_Serialize = {
	/**  配置中的 server 名（前端展示用）。 */
	name: string,
	/**  是否连接成功。 */
	connected: boolean,
	/**  注册的工具数量（连接成功时）。 */
	tool_count: number,
	/**  失败原因（连接失败时）。 */
	error?: string | null,
};

/**  工具定义（前端展示用）。parameters 为 JSON Schema 字符串（serde_json::Value 不实现 specta::Type）。 */
export type McpToolDef = {
	name: string,
	description: string,
	/**  JSON Schema（序列化字符串，前端 JSON.parse 后用） */
	parameters: string,
};

/**  消息角色。对应 Rig `Message` 的三个变体（rig::completion::message::Message）。 */
export type MessageRole = "user" | "assistant" | "system";

/**
 *  消息行（DB 行 ↔ 前端 DTO）。
 * 
 *  `content` 为正文（纯文本/Markdown，流式增量累积）。
 *  `reasoning` 为 reasoning 模型的思考链（独立于正文，前端单独渲染为可折叠块）。
 *  多模态 part、tool call、citation 等结构属二期。
 */
export type MessageRow = MessageRow_Serialize | MessageRow_Deserialize;

/**
 *  消息行（DB 行 ↔ 前端 DTO）。
 * 
 *  `content` 为正文（纯文本/Markdown，流式增量累积）。
 *  `reasoning` 为 reasoning 模型的思考链（独立于正文，前端单独渲染为可折叠块）。
 *  多模态 part、tool call、citation 等结构属二期。
 */
export type MessageRow_Deserialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	status: MessageStatus,
	content: string,
	/**  reasoning 模型的思考链（仅 assistant，可空）。独立于 content，前端单独展示。 */
	reasoning: string | null,
	/**  status=error 时的错误信息，可空 */
	error: string | null,
	/**  assistant 消息记录所用模型，可空 */
	model: string | null,
	created_at: number,
	updated_at: number,
	/**  二期 B1：provider 报告的输入 token（含历史+本轮 prompt）。可空（未报告/旧消息）。 */
	prompt_tokens: number,
	/**  二期 B1：provider 报告的输出 token。可空。 */
	completion_tokens: number,
	/**  二期 B1：provider 报告的总 token。可空。 */
	total_tokens: number,
};

/**
 *  消息行（DB 行 ↔ 前端 DTO）。
 * 
 *  `content` 为正文（纯文本/Markdown，流式增量累积）。
 *  `reasoning` 为 reasoning 模型的思考链（独立于正文，前端单独渲染为可折叠块）。
 *  多模态 part、tool call、citation 等结构属二期。
 */
export type MessageRow_Serialize = {
	id: string,
	conversation_id: string,
	role: MessageRole,
	status: MessageStatus,
	content: string,
	/**  reasoning 模型的思考链（仅 assistant，可空）。独立于 content，前端单独展示。 */
	reasoning?: string | null,
	/**  status=error 时的错误信息，可空 */
	error?: string | null,
	/**  assistant 消息记录所用模型，可空 */
	model?: string | null,
	created_at: number,
	updated_at: number,
	/**  二期 B1：provider 报告的输入 token（含历史+本轮 prompt）。可空（未报告/旧消息）。 */
	prompt_tokens?: number,
	/**  二期 B1：provider 报告的输出 token。可空。 */
	completion_tokens?: number,
	/**  二期 B1：provider 报告的总 token。可空。 */
	total_tokens?: number,
};

/**
 *  消息状态机（见 ARCHITECTURE.md §十五 对话状态机）。
 * 
 *  streaming → complete | error | cancelled
 */
export type MessageStatus = 
/**  流式产出中 */
"streaming" | 
/**  正常完成 */
"complete" | 
/**  出错（附 error 字段） */
"error" | 
/**  用户中断（已产出内容保留为 partial） */
"cancelled";

/**  会话已挂载文档的摘要（不含全文，前端 Inspector 展示用）。 */
export type MountedDocDto = {
	path: string,
	name: string,
	format: string,
	char_count: number,
	mounted_at: number,
};

/**
 *  本体变更日志条目（git commit log 式）。
 *  每条记录一次 import/delete 后的设计说明：title+body 为人可读的 commit message,
 *  change_summary 为机器可读的实体级 +/−/~ 摘要。
 */
export type OntologyChangelog = OntologyChangelog_Serialize | OntologyChangelog_Deserialize;

/**
 *  本体变更日志条目（git commit log 式）。
 *  每条记录一次 import/delete 后的设计说明：title+body 为人可读的 commit message,
 *  change_summary 为机器可读的实体级 +/−/~ 摘要。
 */
export type OntologyChangelog_Deserialize = {
	revision: number,
	title: string,
	body: string,
	/**  JSON 字符串：{"created":[...],"deleted":[...],"modified":[...]} */
	change_summary: string,
	/**  来源会话 id（可空，手工导入无） */
	conversation_id?: string | null,
	/**  "agent" | "user" */
	author: string,
	/**  unix ms */
	created_at: number,
};

/**
 *  本体变更日志条目（git commit log 式）。
 *  每条记录一次 import/delete 后的设计说明：title+body 为人可读的 commit message,
 *  change_summary 为机器可读的实体级 +/−/~ 摘要。
 */
export type OntologyChangelog_Serialize = {
	revision: number,
	title: string,
	body: string,
	/**  JSON 字符串：{"created":[...],"deleted":[...],"modified":[...]} */
	change_summary: string,
	/**  来源会话 id（可空，手工导入无） */
	conversation_id?: string | null,
	/**  "agent" | "user" */
	author: string,
	/**  unix ms */
	created_at: number,
};

/**
 *  本体设计宪章（不变点，1:1 关联本体）。
 * 
 *  与 changelog（变化点）分离：changelog 记每次变更随历史增长，charter 记业务
 *  本质说明不随历史变化。由独立命令 `set_ontology_charter` 写入，不进 import 流程。
 * 
 *  四字段语义（决策：本体不变点）：
 *  - `business_scenario`：业务场景（服务于什么业务目标、谁用、解决什么问题）
 *  - `business_essence`：业务本质（核心业务对象/状态/关系/动态行为的一句话本质概括）
 *  - `design_intent`：设计意图（为什么这样建模、够用且可扩展的取舍、可扩展方向）
 *  - `invariants`：补充说明（自由文本，记录不可违反的业务约束、边界条件等）
 */
export type OntologyCharter = {
	business_scenario?: string,
	business_essence?: string,
	design_intent?: string,
	invariants?: string,
	/**  "agent" | "user" */
	updated_by?: string,
	/**  unix ms */
	updated_at: number,
};

/**  本体列表项（轻量摘要，用于 list_ontologies command）。 */
export type OntologySummary = {
	api_name: string,
	display_name: string,
	description?: string,
};

/**
 *  Provider 配置（前端设置页填写，存 SQLite；敏感字段见 §20.9 加密存）。
 * 
 *  一期：单 provider。二期：多 provider 矩阵。
 * 
 *  字段分四组：
 *    1. **连接**：kind / api_key / base_url / model
 *    2. **采样**：temperature / max_tokens / top_p（rig AgentBuilder 原生）
 *    3. **兼容性**：supports_developer_role / supports_reasoning_effort / input_types
 *       （对齐 pi compat，Ollama/vLLM 等需声明）
 *    4. **增强**：context_window / preamble / extra_headers / reasoning
 */
export type ProviderConfig = ProviderConfig_Serialize | ProviderConfig_Deserialize;

/**
 *  Provider 配置（前端设置页填写，存 SQLite；敏感字段见 §20.9 加密存）。
 * 
 *  一期：单 provider。二期：多 provider 矩阵。
 * 
 *  字段分四组：
 *    1. **连接**：kind / api_key / base_url / model
 *    2. **采样**：temperature / max_tokens / top_p（rig AgentBuilder 原生）
 *    3. **兼容性**：supports_developer_role / supports_reasoning_effort / input_types
 *       （对齐 pi compat，Ollama/vLLM 等需声明）
 *    4. **增强**：context_window / preamble / extra_headers / reasoning
 */
export type ProviderConfig_Deserialize = {
	kind: ProviderKind,
	/**  API Key（明文，一期；二期落 Rust 侧加密存储） */
	api_key: string,
	/**  自定义 base URL。None 则用 provider 默认（rig 内置各 provider 的 BASE_URL 常量）。 */
	base_url: string | null,
	/**  模型名，如 "gpt-4o" / "claude-sonnet-4-5" / "deepseek-chat" / "gemini-2.5-pro" */
	model: string,
	/**  采样温度。知识工作台常需低温度（factual 输出）。None 用 provider 默认。 */
	temperature?: number | null,
	/**
	 *  最大输出 token 数。区别于 context_window（输入窗口）。
	 *  None 时 Anthropic 用 provider 默认（4096）；OpenAI 不设（无上限）。
	 */
	max_tokens?: number,
	/**  nucleus sampling。None 不设。走 additional_params 透传。 */
	top_p?: number | null,
	/**
	 *  是否支持 `developer` role。false 时降级为 `system` message（Ollama/vLLM 等）。
	 *  None 用 kind 默认（OpenAI 官方 true，兼容端点 false）。
	 */
	supports_developer_role?: boolean | null,
	/**
	 *  是否支持 `reasoning_effort` 参数。false 时 drop（兼容端点不认）。
	 *  None 用 kind 默认。
	 */
	supports_reasoning_effort?: boolean | null,
	/**  模型支持输入模态。默认 [Text]；多模态模型填 [Text, Image]。 */
	input_types?: InputType[],
	/**
	 *  模型上下文窗口（token 数）。可选，用户显式覆盖。
	 * 
	 *  优先级最高（见 context_window::resolve_context_window）：
	 *    用户配置 > 官方元数据探测（按 kind 分派）> 内置已知模型表 > 默认 100K
	 *  None 时自动探测（OpenRouter/Anthropic/Gemini 读官方字段；
	 *  DeepSeek 等无官方元数据的模型走内置表）。
	 *  探测全程超时+错误保护，不影响对话主流程；真正的安全网是运行时
	 *  usage + overflow 错误恢复（见 chat.rs / 决策 16）。
	 */
	context_window?: number,
	/**
	 *  系统人设（preamble）。可选，用户在设置页配置。
	 * 
	 *  Skill 系统首次引入 preamble 机制（决策 20）：系统人设 + Skill Tier 1
	 *  （<available_skills> 块）拼接为完整 preamble，注入 AgentBuilder::preamble。
	 *  拼在系统人设后，不破坏 prefix cache（前缀不变，skill 段是后缀追加）。
	 *  None 时仅用 skill 段（若无 skill 则无 preamble）。
	 */
	preamble?: string | null,
	/**
	 *  自定义 HTTP Header（代理、OpenRouter X-Title、Anthropic anthropic_betas 等）。
	 *  键值对，构造 client 时合并进 `Client::builder().http_headers()`。
	 */
	extra_headers?: { [key in string]: string } | null,
	/**  深度思考配置。None 等同 Off。 */
	reasoning?: ReasoningLevel | null,
};

/**
 *  Provider 配置（前端设置页填写，存 SQLite；敏感字段见 §20.9 加密存）。
 * 
 *  一期：单 provider。二期：多 provider 矩阵。
 * 
 *  字段分四组：
 *    1. **连接**：kind / api_key / base_url / model
 *    2. **采样**：temperature / max_tokens / top_p（rig AgentBuilder 原生）
 *    3. **兼容性**：supports_developer_role / supports_reasoning_effort / input_types
 *       （对齐 pi compat，Ollama/vLLM 等需声明）
 *    4. **增强**：context_window / preamble / extra_headers / reasoning
 */
export type ProviderConfig_Serialize = {
	kind: ProviderKind,
	/**  API Key（明文，一期；二期落 Rust 侧加密存储） */
	api_key: string,
	/**  自定义 base URL。None 则用 provider 默认（rig 内置各 provider 的 BASE_URL 常量）。 */
	base_url?: string | null,
	/**  模型名，如 "gpt-4o" / "claude-sonnet-4-5" / "deepseek-chat" / "gemini-2.5-pro" */
	model: string,
	/**  采样温度。知识工作台常需低温度（factual 输出）。None 用 provider 默认。 */
	temperature?: number | null,
	/**
	 *  最大输出 token 数。区别于 context_window（输入窗口）。
	 *  None 时 Anthropic 用 provider 默认（4096）；OpenAI 不设（无上限）。
	 */
	max_tokens?: number,
	/**  nucleus sampling。None 不设。走 additional_params 透传。 */
	top_p?: number | null,
	/**
	 *  是否支持 `developer` role。false 时降级为 `system` message（Ollama/vLLM 等）。
	 *  None 用 kind 默认（OpenAI 官方 true，兼容端点 false）。
	 */
	supports_developer_role?: boolean | null,
	/**
	 *  是否支持 `reasoning_effort` 参数。false 时 drop（兼容端点不认）。
	 *  None 用 kind 默认。
	 */
	supports_reasoning_effort?: boolean | null,
	/**  模型支持输入模态。默认 [Text]；多模态模型填 [Text, Image]。 */
	input_types: InputType[],
	/**
	 *  模型上下文窗口（token 数）。可选，用户显式覆盖。
	 * 
	 *  优先级最高（见 context_window::resolve_context_window）：
	 *    用户配置 > 官方元数据探测（按 kind 分派）> 内置已知模型表 > 默认 100K
	 *  None 时自动探测（OpenRouter/Anthropic/Gemini 读官方字段；
	 *  DeepSeek 等无官方元数据的模型走内置表）。
	 *  探测全程超时+错误保护，不影响对话主流程；真正的安全网是运行时
	 *  usage + overflow 错误恢复（见 chat.rs / 决策 16）。
	 */
	context_window?: number,
	/**
	 *  系统人设（preamble）。可选，用户在设置页配置。
	 * 
	 *  Skill 系统首次引入 preamble 机制（决策 20）：系统人设 + Skill Tier 1
	 *  （<available_skills> 块）拼接为完整 preamble，注入 AgentBuilder::preamble。
	 *  拼在系统人设后，不破坏 prefix cache（前缀不变，skill 段是后缀追加）。
	 *  None 时仅用 skill 段（若无 skill 则无 preamble）。
	 */
	preamble?: string | null,
	/**
	 *  自定义 HTTP Header（代理、OpenRouter X-Title、Anthropic anthropic_betas 等）。
	 *  键值对，构造 client 时合并进 `Client::builder().http_headers()`。
	 */
	extra_headers?: { [key in string]: string } | null,
	/**  深度思考配置。None 等同 Off。 */
	reasoning?: ReasoningLevel | null,
};

/**
 *  一期支持的 provider 种类。
 * 
 *  按 kind 路由到 rig 原生 provider client，而非全部塞进 `openai::Client`——
 *  这样每个 provider 的 capability（`SUPPORTS_TOOLS`/`SUPPORTS_RESPONSE_FORMAT`/
 *  `EMITS_COMPLETE_SINGLE_CHUNK_TOOL_CALLS`/`STREAM_INCLUDE_USAGE`）由 rig 正确声明，
 *  避免 DeepSeek 单 chunk tool call 渲染异常、response_format 被错误发送等问题。
 * 
 *  `OpenAiCompatible` 是兜底：未知兼容端点（用户自定义 base_url）。
 */
export type ProviderKind = 
/**  OpenAI 官方端点，走 Responses API（rig `openai::Client` 默认） */
"openai" | 
/**  Anthropic（Claude 系） */
"anthropic" | 
/**  Google Gemini（Generative AI 协议，非 OpenAI 兼容） */
"gemini" | 
/**  DeepSeek（OpenAI 兼容，单 chunk tool call + 不支持 response_format） */
"deepseek" | 
/**  xAI Grok */
"xai" | 
/**  Groq（超低延迟推理） */
"groq" | 
/**  OpenRouter（多模型聚合） */
"openrouter" | 
/**  Ollama（本地） */
"ollama" | 
/**  Moonshot / Kimi */
"moonshot" | 
/**  智谱 GLM（Z.AI，rig `zai` provider，OpenAI 兼容协议 + thinking 参数） */
"zhipu" | 
/**  Mistral */
"mistral" | 
/**  Cohere */
"cohere" | 
/**  Perplexity（在线搜索，不支持工具） */
"perplexity" | 
/**  兜底：未知 OpenAI 兼容端点（用户自定义 base_url） */
"openai_compatible";

/**  查询结果（execute_sql / run_query 返回）。 */
export type QueryResult = QueryResult_Serialize | QueryResult_Deserialize;

/**  查询结果（execute_sql / run_query 返回）。 */
export type QueryResult_Deserialize = {
	columns: ColumnMeta[],
	/**
	 *  Arrow 行 → JSON 字符串数组（每行一个 JSON 对象字符串，前端 JSON.parse）。
	 *  用 String 而非 serde_json::Value：对齐 mcp.rs 范式（Value 不实现 specta::Type）。
	 */
	rows: string[],
	row_count: number,
	elapsed_ms: number,
	/**  透明性：查询涉及的源（catalog 名）。 */
	sources_touched: string[],
	/**  SQL 执行计划摘要（EXPLAIN，调试/审计用，可选）。 */
	explain?: string | null,
};

/**  查询结果（execute_sql / run_query 返回）。 */
export type QueryResult_Serialize = {
	columns: ColumnMeta[],
	/**
	 *  Arrow 行 → JSON 字符串数组（每行一个 JSON 对象字符串，前端 JSON.parse）。
	 *  用 String 而非 serde_json::Value：对齐 mcp.rs 范式（Value 不实现 specta::Type）。
	 */
	rows: string[],
	row_count: number,
	elapsed_ms: number,
	/**  透明性：查询涉及的源（catalog 名）。 */
	sources_touched: string[],
	/**  SQL 执行计划摘要（EXPLAIN，调试/审计用，可选）。 */
	explain?: string | null,
};

/**
 *  深度思考级别（对齐 pi thinkingLevelMap 的简化版）。
 * 
 *  - Off：不启用（默认）
 *  - Low / Medium / High：按 provider 映射为 `reasoning_effort` 或 `thinking.budget_tokens`
 * 
 *  不引入 pi 的 minimal/xhigh/max 七级——onto-studio 是知识工作台非编码 agent，
 *  三档足够；后续可扩。
 */
export type ReasoningLevel = "off" | "low" | "medium" | "high";

/**  schema 快照（browse_schema / test_data_source 返回）。 */
export type SchemaSnapshot = SchemaSnapshot_Serialize | SchemaSnapshot_Deserialize;

/**  schema 快照（browse_schema / test_data_source 返回）。 */
export type SchemaSnapshot_Deserialize = {
	tables: TableMeta_Deserialize[],
};

/**  schema 快照（browse_schema / test_data_source 返回）。 */
export type SchemaSnapshot_Serialize = {
	tables: TableMeta_Serialize[],
};

/**  发送消息的输入（对齐 §13.2 SendMessageRequest 一期子集）。 */
export type SendMessageInput = {
	conversation_id: string,
	/**  纯文本内容（一期；多模态图片输入下一步加 image 字段） */
	content: string,
	/**
	 *  本次携带的挂载文档路径列表（用户在消息中 `@fileName` 引用的文档）。
	 *  后端不从这些文档读全文注入 prompt——而是查得每篇的 id+name，
	 *  在 user message 尾部追加 `<mounted-documents>` 注脚，模型按需调
	 *  `read_document(id)` 工具取全文（agentic search，cache 友好）。
	 */
	mounted_paths?: string[],
	/**  本次携带的图片上下文（选中的已摄入图片，走 VLM）。 */
	context_images?: ContextImageInput[],
	/**
	 *  是否开启深度思考（reasoning）。true 时按 provider kind 透传
	 *  reasoning_effort/thinking 参数。默认 false。
	 */
	enable_reasoning?: boolean,
};

/**  用于将消息标记为错误/取消的辅助命令（前端重试/中断后收尾用）。 */
export type SetMessageStatusInput = SetMessageStatusInput_Serialize | SetMessageStatusInput_Deserialize;

/**  用于将消息标记为错误/取消的辅助命令（前端重试/中断后收尾用）。 */
export type SetMessageStatusInput_Deserialize = {
	message_id: string,
	status: MessageStatus,
	error: string | null,
};

/**  用于将消息标记为错误/取消的辅助命令（前端重试/中断后收尾用）。 */
export type SetMessageStatusInput_Serialize = {
	message_id: string,
	status: MessageStatus,
	error?: string | null,
};

export type SetPinnedInput = {
	id: string,
	pinned: boolean,
};

/**
 *  设置页输入的 provider 配置（API Key 明文传，Rust 侧落盘）。
 * 
 *  字段对齐 `ProviderConfig`，一期一期二期逐步补全。
 */
export type SetProviderInput = SetProviderInput_Serialize | SetProviderInput_Deserialize;

/**
 *  设置页输入的 provider 配置（API Key 明文传，Rust 侧落盘）。
 * 
 *  字段对齐 `ProviderConfig`，一期一期二期逐步补全。
 */
export type SetProviderInput_Deserialize = {
	kind: ProviderKind,
	api_key: string,
	base_url: string | null,
	model: string,
	temperature?: number | null,
	max_tokens?: number,
	top_p?: number | null,
	supports_developer_role?: boolean | null,
	supports_reasoning_effort?: boolean | null,
	input_types?: InputType[],
	/**  模型上下文窗口（token 数），可选。None 时自动探测。 */
	context_window?: number,
	/**  系统人设（preamble），可选。None = 无系统人设（仅 skill 段作 preamble）。 */
	preamble?: string | null,
	/**  自定义 HTTP Header（代理、X-Title、anthropic_betas 等）。 */
	extra_headers?: { [key in string]: string } | null,
	/**  深度思考级别（运行时 Composer toggle 会覆盖为 High/Off）。 */
	reasoning?: ReasoningLevel | null,
};

/**
 *  设置页输入的 provider 配置（API Key 明文传，Rust 侧落盘）。
 * 
 *  字段对齐 `ProviderConfig`，一期一期二期逐步补全。
 */
export type SetProviderInput_Serialize = {
	kind: ProviderKind,
	api_key: string,
	base_url?: string | null,
	model: string,
	temperature?: number | null,
	max_tokens?: number,
	top_p?: number | null,
	supports_developer_role?: boolean | null,
	supports_reasoning_effort?: boolean | null,
	input_types: InputType[],
	/**  模型上下文窗口（token 数），可选。None 时自动探测。 */
	context_window?: number,
	/**  系统人设（preamble），可选。None = 无系统人设（仅 skill 段作 preamble）。 */
	preamble?: string | null,
	/**  自定义 HTTP Header（代理、X-Title、anthropic_betas 等）。 */
	extra_headers?: { [key in string]: string } | null,
	/**  深度思考级别（运行时 Composer toggle 会覆盖为 High/Off）。 */
	reasoning?: ReasoningLevel | null,
};

/**
 *  前端展示用的 Skill DTO。
 * 
 *  合并了扫描结果（SkillRecord）+ 激活状态（全局禁用/会话级 enabled）。
 */
export type SkillDto = {
	name: string,
	description: string,
	source: SkillSource,
	disable_model_invocation: boolean,
	license: string | null,
	compatibility: string | null,
	allowed_tools: string[] | null,
	/**
	 *  本会话是否激活（会话级 enabled 状态；None=无会话级记录，按 source 默认行为）。
	 *  前端据此显示开关初始态。
	 */
	conversation_enabled: boolean | null,
	/**  是否全局禁用（层次 2）。 */
	globally_disabled: boolean,
};

/**
 *  Skill 来源（对应 conversation_skills.source 列）。
 * 
 *  kebab-case 序列化，specta 导出为 TS 字符串字面量联合类型。
 */
export type SkillSource = 
/**  随应用分发，只读（resource_dir/skills/） */
"builtin" | 
/**  用户导入，可读写（~/.onto-studio/skills/） */
"imported" | 
/**  跨客户端扫描，只读（~/.agents/skills/ 等） */
"external-read-only" | 
/**  项目级（二期，需先定义"工作区"概念） */
"project";

/**  流式 chunk 种类。 */
export type StreamKind = 
/**  文本增量 */
"text_delta" | 
/**  思考/reasoning 增量（reasoning 模型） */
"reasoning_delta" | 
/**
 *  工具调用开始（模型决定调用某工具，即将执行）
 *  `text` = 工具名；`tool_call` 附带调用详情
 */
"tool_call_start" | 
/**
 *  工具调用结果（执行完成）
 *  `text` = 结果文本（模型可见）；`tool_call` 附带调用详情与结果
 */
"tool_call_result" | 
/**
 *  provider 报告的真实 token usage（二期 B1）
 *  `usage` 附带输入/输出/总 token；可在 Done 前多次发出（多轮工具调用）
 */
"usage" | 
/**  流式正常结束 */
"done" | 
/**  出错结束 */
"error";

/**  表元信息。 */
export type TableMeta = TableMeta_Serialize | TableMeta_Deserialize;

/**  表元信息。 */
export type TableMeta_Deserialize = {
	name: string,
	columns: ColumnMeta[],
	/**  行数估计（information_schema 或 COUNT(*)，可能为 None）。 */
	row_count_estimate: number,
	/**
	 *  前 5 行样本（describe_table 返回；list 时不带）。
	 *  每行为 JSON 序列化字符串（对齐 mcp.rs 范式：serde_json::Value 不实现 specta::Type）。
	 */
	sample_rows?: string[],
};

/**  表元信息。 */
export type TableMeta_Serialize = {
	name: string,
	columns: ColumnMeta[],
	/**  行数估计（information_schema 或 COUNT(*)，可能为 None）。 */
	row_count_estimate?: number,
	/**
	 *  前 5 行样本（describe_table 返回；list 时不带）。
	 *  每行为 JSON 序列化字符串（对齐 mcp.rs 范式：serde_json::Value 不实现 specta::Type）。
	 */
	sample_rows?: string[],
};

/**
 *  provider 报告的真实 token usage（二期 B1）。
 * 
 *  随 `StreamChunk::Usage` 发出，供上层落库到 assistant 消息，
 *  下次发消息前用于压缩判定（替代 chars/4 估算）。
 */
export type TokenUsage = {
	input_tokens: number,
	output_tokens: number,
	total_tokens: number,
};

/**  工具调用详情（随 ToolCallStart/ToolCallResult 一起发出）。 */
export type ToolCallInfo = {
	/**  工具名（MCP server 注册的 name） */
	name: string,
	/**  模型传入的 JSON 参数（原始字符串） */
	arguments: string,
	/**  Rig 内部调用 ID（同一轮多个调用可关联） */
	call_id: string,
	/**  工具结果（仅 ToolCallResult 时有意义，ToolCallStart 为 None） */
	result: string | null,
	/**  是否出错（工具报告 is_error 或执行异常） */
	is_error: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

